import { radius, spacing, makeStyles } from '../../theme';

export const useStyles = makeStyles(({ colors, shadows }) => ({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerAddBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.glow,
  },
  tabsScroller: {
    marginBottom: spacing.md,
    flexGrow: 0,
  },
  tabsRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    paddingRight: spacing.lg,
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    minHeight: 40,
    borderRadius: radius.full,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
  },
  tabItemActive: {
    backgroundColor: colors.surface,
    borderColor: 'transparent',
    ...shadows.elevated,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabLabelActive: {
    color: colors.primaryLight,
    fontWeight: '800',
  },
  scrollContent: {
    padding: spacing.lg,
  },
  sectionWrap: {
    gap: spacing.lg,
  },
  heroStatCard: {
    backgroundColor: colors.primarySurface ?? colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderGlow ?? colors.border,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    ...shadows.glow,
  },
  heroStatHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  heroStatLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  heroStatCaption: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
    flexShrink: 1,
    marginLeft: spacing.sm,
  },
  heroStatValue: {
    fontSize: 40,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  heroStatUnit: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textMuted,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 6,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 68,
  },
  kpiCardMuted: {
    borderStyle: 'dashed',
    backgroundColor: 'transparent',
  },
  kpiSetLink: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryLight,
  },
  kpiLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 4,
    textAlign: 'center',
  },
  kpiCaption: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: 2,
    textAlign: 'center',
  },
  kpiValue: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  kpiUnit: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textMuted,
  },
  deltaValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    maxWidth: '100%',
  },
  deltaText: {
    flexShrink: 1,
  },
  textSuccess: {
    color: colors.primaryLight,
  },
  textWarning: {
    color: colors.amber,
  },
  textTarget: {
    color: colors.cyan,
  },
  chartCard: {
    padding: spacing.md,
  },
  skeletonLineSm: {
    width: 90,
    height: 10,
    borderRadius: radius.sm,
    backgroundColor: colors.borderSubtle,
    marginBottom: spacing.sm,
  },
  skeletonLineLg: {
    width: 140,
    height: 32,
    borderRadius: radius.sm,
    backgroundColor: colors.borderSubtle,
  },
  skeletonChart: {
    height: 220,
    marginTop: spacing.lg,
    backgroundColor: colors.surface,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  cardEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  chartContainer: {
    alignItems: 'center',
    marginTop: spacing.xs,
    position: 'relative',
    width: '100%',
  },
  periodFilterWrap: {
    marginBottom: spacing.sm,
  },
  tooltipExtraRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
    marginTop: 3,
  },
  tooltipExtraLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  tooltipExtraValue: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  chartControlBar: {
    width: '100%',
    gap: 6,
    marginBottom: spacing.sm,
    paddingHorizontal: 4,
  },
  chartMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  chartTrendPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
  },
  chartTrendPillLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  chartTrendPillValue: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primaryLight,
  },
  chartRatePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: radius.sm,
    borderWidth: 1,
  },
  pillSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  pillWarning: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderColor: 'rgba(245, 158, 11, 0.25)',
  },
  pillNeutral: {
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.borderSubtle,
  },
  chartRatePillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  logPrCard: {
    padding: spacing.md,
    borderRadius: radius.lg,
  },
  formTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  prFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  prInput: {
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  selectedExercisePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primarySurface,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    marginBottom: spacing.sm,
  },
  selectedExerciseName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryLight,
  },
  exerciseChipsScroll: {
    marginBottom: spacing.sm,
  },
  exerciseChip: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: radius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: 5,
    marginRight: 6,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
  },
  exerciseChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  prInputsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  savePrBtn: {
    marginTop: spacing.sm,
  },
  prBadgeWrapper: {
    alignItems: 'flex-end',
    gap: 4,
  },
  celebratePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  celebratePillText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#F59E0B',
  },
  logFormCard: {
    padding: spacing.md,
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  formTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  formInputsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  formInputSpacing: {
    marginBottom: spacing.sm,
  },
  formRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  flex1: {
    flex: 1,
  },
  flex2: {
    flex: 2,
  },
  flex3: {
    flex: 3,
  },
  half: {
    flex: 1,
  },
  saveBtn: {
    marginTop: spacing.md,
  },
  historyWrap: {
    gap: spacing.sm,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  sectionMeta: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '600',
  },
  quickAddLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  quickAddLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryLight,
  },
  historyList: {
    gap: spacing.xs,
  },
  showMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: spacing.sm,
  },
  showMoreText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primaryLight,
  },
  historyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyLeft: {
    gap: 2,
  },
  historyDateBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  historyDate: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  historyIsoDate: {
    fontSize: 11,
    color: colors.textMuted,
  },
  historyRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  historyWeightCol: {
    alignItems: 'flex-end',
  },
  historyWeightVal: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  historyWeightUnit: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
  },
  historyDiff: {
    fontSize: 11,
    fontWeight: '700',
  },
  historyDeleteBtn: {
    padding: spacing.xs,
  },
  swipeDelete: {
    width: 96,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: colors.error,
    borderRadius: radius.md,
    marginVertical: 4,
  },
  swipeDeleteText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    padding: 0,
  },
  filterChipRow: {
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipActive: {
    backgroundColor: colors.primarySurface,
    borderColor: colors.primaryLight,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  filterChipTextActive: {
    color: colors.primaryLight,
    fontWeight: '800',
  },
  prList: {
    gap: spacing.sm,
  },
  prItemCard: {
    padding: spacing.md,
  },
  prHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  prIconBox: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    backgroundColor: colors.amberGlow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  prHeaderInfo: {
    flex: 1,
  },
  prExerciseName: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  prMuscle: {
    fontSize: 12,
    color: colors.textMuted,
  },
  prStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.borderSubtle,
  },
  prStatCol: {
    alignItems: 'center',
  },
  prStatLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  prStatVal: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  prStatValDate: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  prStatUnit: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
  },
  prDivider: {
    width: 1,
    height: 24,
    backgroundColor: colors.border,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  metricCard: {
    width: '48.5%',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  metricCardLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  metricCardValue: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.textPrimary,
    marginTop: 4,
  },
  metricCardUnit: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  metricCardDeltaRow: {
    marginTop: 6,
  },
  metricCardDeltaText: {
    fontSize: 11,
    fontWeight: '700',
  },
  metricCardSub: {
    fontSize: 11,
    color: colors.textMuted,
  },
  mLogList: {
    gap: spacing.sm,
  },
  mLogCard: {
    padding: spacing.md,
  },
  mLogHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  mPillGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  mPill: {
    flexDirection: 'row',
    gap: 4,
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.sm,
    alignItems: 'center',
  },
  mPillLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
  },
  mPillVal: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  mNotesText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
    marginTop: spacing.sm,
  },
}));
